# Requiremnts.txt

[package]
name = "fast_snake_v6"
version = "0.1.0"
edition = "2021"

#（.pyd/.so）instead of (.exe)
[lib]
name = "fast_snake_v6"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
numpy = "0.20"
rand = "0.8"
rayon = "1.8"